title: blogAdrian
baseurl: ""
url: "https://blogadrian.com"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag



nav_pages:
    - about.md

sass:
  sass_dir: sass
  style: compressed

excerpt_separator: ""